model_priorities:
  info_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:
    
  message_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:


  review_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  summerize_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  user_data_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  story_gm_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  story_character_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  story_summary_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:

  story_outline_model:
    - google:
      - gemini-2.5-flash
      - gemini-2.5-flash-lite
      - gemini-2.0-flash
      - gemini-2.0-flash-lite
    - ollama:
    - openai:
    - anthropic:
